### ISSUE TITLE
Small idea - usr/doc file locations

### ISSUE THREAD

**Issue by edrozenberg** [zuno/slackpkgplus#15]
For my own aesthetic reasons :) I like to re-org various items from `doc/` as follows and create my own custom pkg with these small changes. I also mod doinst.sh appropriately:

```
usr/doc/slackpkg+-1.7.4
    CHANGES
    ChangeLog.txt
    README

usr/share/slackpkg+
    build
        slackpkg+.SlackBuild
    config
        slackpkgplus.x86.sample
        slackpkgplus.x86_64.sample
    repos
        repositories.lst
        repositories.txt
    scripts
        checkrepos.sh
        setupmultilib.sh
```

**Comment by zuno** [comment]
slackpkg+ try to be similar as possible to slackpkg, where the 'sample' file are in doc.
repositories.* IS just documentation
I always add the slackbuild only for documentation about package creation since it is not really useful to build it
checkrepos.sh is a script to expand repositories.txt
setupmultilib.sh is a script that use the user to configure multilib.
The user usually should not search piece of packages in /usr/share, so /usr/doc is the best option.

**Comment by edrozenberg** [comment]
@zuno thanks for your explanation. I'll keep mangling it in my own way but understand the standard approach.
